name: flutter_training
description: Demo Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/image01.JPG
  - images/image02.JPG
  - images/image03.JPG
  - images/image04.JPG
  - images/image05.JPG
  - images/image06.JPG
  - images/image07.JPG
  - images/image08.JPG
  - images/image09.JPG
  - images/image10.JPG
  - images/image11.JPG
  - images/image12.JPG
  - images/image13.JPG
  - images/image14.JPG
  - images/image15.JPG
  - images/image16.JPG
  - images/image17.JPG
  - images/image18.JPG
  - images/image19.JPG
  - images/image20.JPG
  - images/image21.JPG
  - images/image22.JPG
  - images/image23.JPG
  - images/image24.JPG
  - images/image25.JPG
  - images/image26.JPG
  - images/image27.JPG
  - images/image28.JPG
  - images/image29.JPG
  - images/phongTom.jpg
  - images/Garou.jpg
